### ISSUE TITLE
Python 3.8 deprecation warnings

### ISSUE THREAD

**Issue by davesteele** [Tinche/aiofiles#70]
e.g.
  /home/daves/github/aiofiles/.pybuild/cpython3_3.8/build/aiofiles/threadpool/utils.py:33: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def method(self, *args, **kwargs):

.pybuild/cpython3_3.8/build/tests/test_simple.py::test_serve_small_bin_file_sync
  /home/daves/github/aiofiles/.pybuild/cpython3_3.8/build/tests/test_simple.py:28: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    server = yield from asyncio.start_server(serve_file, port=unused_tcp_port,

**Comment by fakegermano** [comment]
I have this warning too, but they explicitly state that they only support up to python 3.7
But I believe supporting 3.8 is in the roadmap, and fixing this issue will be necessary for that step.

**Comment by Tinche** [comment]
I believe these are fixed in the latest release!

**Comment by colidyre** [comment]
> I believe these are fixed in the latest release!

@Tinche Do you mean on the master branch instead of the tagged release? I have also DeprecationWarning with Pytest on os.py:8 with the latest release 0.5.0 as already mentioned in #74 (which mentioned also #75 and #54).

See the differences for [master](https://github.com/Tinche/aiofiles/blob/master/aiofiles/os.py#L8-L9) and [latest release 0.5.0](https://github.com/Tinche/aiofiles/blob/v0.5.0/aiofiles/os.py#L8-L10) for example. It would be nice to have a tagged version to get rid of the Python3.8 warnings for this version.

**Comment by samuelcolvin** [comment]
@Tinche any chance you could create a new release to include the fix for this?

**Comment by Tinche** [comment]
I'll cut a new release tomorrow!

**Comment by Tinche** [comment]
Released!

**Comment by samuelcolvin** [comment]
thank you.
